# Хосты-сканеры (где будет запускаться nmap)
[web]
web1 ansible_host=192.168.255.201 ansible_user=ubuntu
web2 ansible_host=192.168.255.202 ansible_user=ubuntu

[targets:children]
web

# Локальный хост для тестирования
# [local]
# localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
nginx_document_root=/var/www/html
