apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

namePrefix: prod-

labels:
  - pairs:
      environment: prod

resources:
  - ../../base

patches:
  - path: flask-deployment-patch.yaml
  - path: flask-env.yaml
  - path: flask-replicas.yaml
  - path: flask-service-patch.yaml
