events {
    worker_connections 1024;
}

http {
    # Базовый сервер (HTTP) - закрывает первую часть задания
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }

    # Дополнительный сервер (HTTPS) - закрывает доп. задание
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}